INCLUDES := -Iinclude
LIBS := -lGLEW -lGLU -lGL -lglut 

SRC_DIR := src
OBJ_DIR := build
SRC_FILES := $(wildcard $(SRC_DIR)/*.cpp)
OBJ_FILES := $(patsubst $(SRC_DIR)/%.cpp,$(OBJ_DIR)/%.o,$(SRC_FILES))
CPPFLAGS := -DGL_SILENCE_DEPRECATION $(INCLUDES)

project: $(OBJ_FILES)
	g++ -o $@ $^ $(LIBS) 

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp
	g++ $(CPPFLAGS) -c -o $@ $<
	
clean:
	rm build/*.o project
